name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: upsert
        with:
          source_json: '[ { "id": 1, "title": "Test 1" }, { "id": 2, "title": "Title 2" }, { "id": 3, "title": "Title 3" } ]'
          input_json: '{ "id": 2, "title": "Test Updated!" }'
          filter_property: id
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "test.json"
          json: ${{ steps.upsert.outputs.json }}
      - if: ${{ steps.upsert.outputs.json != '[{"id":1,"title":"Test 1"},{"id":2,"title":"Test Updated!"},{"id":3,"title":"Title 3"}]' }}
        run: exit 1
